name: bibmin-logic
version: '0.1.0'
category: Web
author: maton
maintainer: automatonix@gmail.com
copyright: Haruki Yokoyama
license: BSD3
github: matonix/bibmin-logic

dependencies:
- base >=4.7 && <5
- containers
- text
- megaparsec
- parser-combinators
ghc-options:
- -Wall

library:
  source-dirs: src

tests:
  bibmin-logic-test:
    main: Driver.hs
    source-dirs: test
    dependencies:
    - bibmin-logic
    - tasty
    - tasty-hunit
    - tasty-golden
    - tasty-discover
    - filepath
