library:
  source-dirs:
  - src
tests:
  doctest:
    source-dirs:
    - test
    main: DocTest.hs
    dependencies:
    - bibmin-tonaserver
    - doctest
    - Glob
    other-modules: []
  spec:
    source-dirs:
    - test
    main: Spec.hs
    dependencies:
    - bibmin-tonaserver
    - hspec
    - QuickCheck
    other-modules: []
copyright: 2019 Yokoyama Haruki
category: Web
maintainer: automatonix@gmail.com
ghc-options: -Wall -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns
  -Wredundant-constraints -Werror
dependencies:
- rio
- th-lift-instances
- yaml
- template-haskell
- megaparsec
- http-api-data
- aeson
- servant
- servant-server
- bibmin-logic
- tonalude
- tonatona
- tonatona-logger
- tonatona-servant
- base >= 4.7 && < 5
default-extensions:
- AutoDeriveTypeable
- BangPatterns
- BinaryLiterals
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveDataTypeable
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- DoAndIfThenElse
- DuplicateRecordFields
- EmptyDataDecls
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- KindSignatures
- LambdaCase
- MonadFailDesugaring
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- NoImplicitPrelude
- OverloadedStrings
- PartialTypeSignatures
- PatternGuards
- PolyKinds
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeFamilies
- TypeSynonymInstances
- ViewPatterns
name: bibmin-tonaserver
version: 0.1.0.0
extra-source-files:
- README.md
author: Yokoyama Haruki
github: yokoyama-haruki/bibmin-tonaserver
license: MIT
executables:
  bibmin-tonaserver:
    source-dirs:
    - app
    main: Main.hs
    dependencies:
    - bibmin-tonaserver
