resolver: lts-13.4
packages:
  - .
  - ../bibmin-logic
extra-deps:
  - git: https://github.com/tonatona-project/tonatona
    commit: bc916ac3bd633075950ac8976282aa7b5c02da4e
    subdirs:
      - tonalude
      - tonaparser
      - tonatona
      - tonatona-logger
      - tonatona-persistent-postgresql
      - tonatona-persistent-sqlite
      - tonatona-servant
  - tasty-hedgehog-0.2.0.0
  - hedgehog-0.6.1

flags: {}
extra-package-dbs: []